version: "3.8"

name: experiment-api

services:
  ai-backend:
    restart: always
    image: ai-backend-image
    ports:
      - "5000:3333"
    networks:
      - backend
    volumes:
      - backend-data:/usr/src/app/artifacts
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:8080

  ai-backend-db:
    image: postgres:16.2
    restart: unless-stopped
    ports:
      - 127.0.0.1:5003:5432
    volumes:
      - ai-backend-db-data:/var/lib/postgresql/data
    env_file:
      - docker.env
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
    networks:
      - backend

  mlflow-server:
    restart: always
    image: mlflow-server-image
    ports:
      - "5001:8080"
    volumes:
      - mlflow-data:/usr/src/app
    networks:
      - backend

  ai-web-app:
    restart: always
    image: ai-web-app-image
    ports:
      - "5002:8080"
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  mlflow-data:
  backend-data:
  ai-backend-db-data:
